In [1]:
import numpy as np
# 从清华源安装
# pip install numpy -i https://pypi.tuna.tsinghua.edu.cn/simple

## create array

In [2]:
x = np.array([[1.5, 2, 3], 
              [4, 5, 6]])
print('shape: ', x.shape)
print('ndim: ', x.ndim)
print('size: ', x.size)
print('dtype', x.dtype)

shape:  (2, 3)
ndim:  2
size:  6
dtype float64


In [3]:
print('zeros:\n', np.zeros((3, 2)))
print('\nones:\n', np.ones((3, 3)))
x = np.eye(3)
print('\neye:\n', x)
print('\nones like:\n', np.ones_like(x))

zeros:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]

ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

eye:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

ones like:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
# vector
print('arange\n', np.arange(10))
print(np.arange(5, 15, 2))
print('\nlinspace\n', np.linspace(1, 2, 10))

arange
 [0 1 2 3 4 5 6 7 8 9]
[ 5  7  9 11 13]

linspace
 [1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


In [5]:
# random
print('uniform\n', np.random.rand(3, 4))
print('\nguassian\n', np.random.randn(3, 4))
print('\none random int\n', np.random.randint(0, 10))
print('\nrandint array\n', np.random.randint(0, 100, (3, 4)))

uniform
 [[0.13844538 0.03842136 0.35128695 0.54724518]
 [0.96249979 0.0404378  0.23281676 0.66480316]
 [0.66651529 0.36771228 0.5071421  0.24533233]]

guassian
 [[ 0.17440339  0.84614031  0.69250583 -0.0596763 ]
 [-1.16652531  1.38948075  0.39470411 -0.97596643]
 [-0.6268671  -1.33545664  0.34820404 -0.34417086]]

one random int
 3

randint array
 [[ 3 29 33 34]
 [28 36 76 39]
 [40 13 22 19]]


## operation

In [6]:
# basic operation
a = np.random.randn(2, 3)
print('origin a:\n', a)

print('\nmatrix and single number * 2')
print(a * 2)

b = np.random.randn(2, 3)
print('\nmatrix and matrix')
print('matrix b:\n', b)
print(a * b)

print('\nmatrix and vector')
vec = np.random.randn(1, 3)
print('vec:',vec)
print('res:\n', a * vec)


origin a:
 [[-1.42683002 -0.4717019  -1.95705259]
 [ 1.25093398  0.28188193  1.63004368]]

matrix and single number * 2
[[-2.85366004 -0.94340379 -3.91410517]
 [ 2.50186795  0.56376386  3.26008737]]

matrix and matrix
matrix b:
 [[ 0.86924728 -0.6474743  -0.62838318]
 [ 1.87907913 -2.20194833 -1.22003834]]
[[-1.24026812  0.30541485  1.22977893]
 [ 2.35060393 -0.62068944 -1.98871579]]

matrix and vector
vec: [[-0.07397123  0.56195062  1.13049213]]
res:
 [[ 0.10554437 -0.26507317 -2.21243255]
 [-0.09253313  0.15840372  1.84275156]]


In [7]:
# matrix multiply
a = np.random.randn(3, 4)
b = np.random.randn(4, 5)
out2 = np.matmul(a, b)
out1 = a @ b
print(out1.shape)
print(out2.shape)
print(out1 == out2)

(3, 5)
(3, 5)
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [8]:
# element wise operation
x = np.random.rand(2, 3)
print('origin x:\n', x)
print('exp ^ x:\n', np.exp(x))
print('sin x:\n', np.sin(x))
print('x square:\n', x ** 2)
print('x sqrt:\n', np.sqrt(x))
print('x log:\n', np.log(x))


origin x:
 [[0.89649866 0.2200615  0.79184094]
 [0.38082242 0.01321333 0.69561177]]
exp ^ x:
 [[2.45100626 1.24615337 2.20745649]
 [1.46348769 1.01330101 2.00493526]]
sin x:
 [[0.78114564 0.21828965 0.71164781]
 [0.37168409 0.01321295 0.64085519]]
x square:
 [[8.03709845e-01 4.84270659e-02 6.27012081e-01]
 [1.45025713e-01 1.74592135e-04 4.83875734e-01]]
x sqrt:
 [[0.94683613 0.46910714 0.88985445]
 [0.61710811 0.11494926 0.83403343]]
x log:
 [[-0.10925848 -1.5138482  -0.23339474]
 [-0.96542211 -4.32652898 -0.36296358]]


In [9]:
x = np.random.randn(2, 2)
print('origin x\n', x)


filt = np.array([[True, False], [True, True]])
print('\nfilt\n', filt)
print(x[filt])


filt = x > 0
print('\nfilt\n', filt)
print('element in x which x > 0:\n', x[filt])

origin x
 [[ 0.52783338 -0.54537236]
 [-0.98843637  0.59292446]]

filt
 [[ True False]
 [ True  True]]
[ 0.52783338 -0.98843637  0.59292446]

filt
 [[ True False]
 [False  True]]
element in x which x > 0:
 [0.52783338 0.59292446]


In [10]:
# concat
x = np.random.randn(2, 3)
y = np.ones_like(x)
print('origin matrix')
print('x\n', x)
print('y\n', y)

print('\nconcat along axis 0\n', np.concatenate([x, y], axis=0))
print('\nconcat along axis 1\n', np.concatenate([x, y], axis=1))

origin matrix
x
 [[-0.44438331 -1.16846156  0.43662578]
 [ 0.58194687 -0.205007    0.11695023]]
y
 [[1. 1. 1.]
 [1. 1. 1.]]

concat along axis 0
 [[-0.44438331 -1.16846156  0.43662578]
 [ 0.58194687 -0.205007    0.11695023]
 [ 1.          1.          1.        ]
 [ 1.          1.          1.        ]]

concat along axis 1
 [[-0.44438331 -1.16846156  0.43662578  1.          1.          1.        ]
 [ 0.58194687 -0.205007    0.11695023  1.          1.          1.        ]]


In [11]:
x = np.random.randn(2, 3)
print('origin x\n', x)
y = x.reshape((1, 6))
print('\nreshape to (1, 6)\n', y)
print('\n x transpose\n', x.T)
print('\n more advanced transpose\n', np.transpose(x, (1, 0)))

origin x
 [[-0.03343653  0.14602599 -0.07859444]
 [ 0.73741927 -1.03719487  0.8030264 ]]

reshape to (1, 6)
 [[-0.03343653  0.14602599 -0.07859444  0.73741927 -1.03719487  0.8030264 ]]

 x transpose
 [[-0.03343653  0.73741927]
 [ 0.14602599 -1.03719487]
 [-0.07859444  0.8030264 ]]

 more advanced transpose
 [[-0.03343653  0.73741927]
 [ 0.14602599 -1.03719487]
 [-0.07859444  0.8030264 ]]


In [18]:
x = np.random.randn(2, 4)
print('origin x\n', x)
print('\nbasic check')
print('min:', x.min(), 'max:', x.max())
print('mean:', x.mean(), 'std:', x.std())
print('\nmean along one axis:\n', np.mean(x, axis=0))
print('\nsum along one axis:\n', np.sum(x, axis=1))
idxs = np.argmin(x, axis=0)
print('\nthe index of min elements\n', idxs)
print('\nselected min elements\n', x[idxs, np.arange(4)])
print('\nsorted index of elements along one aixs\n', np.argsort(x, axis=1))
print('\nsorted array\n', np.sort(x, axis=0))

origin x
 [[-1.47670506  2.09186101 -0.41458314 -0.17787515]
 [ 0.6204501  -0.12454182 -0.70414127 -2.56581807]]

basic check
min: -2.5658180693814883 max: 2.09186101053541
mean: -0.3439191746296401 std: 1.2890656585659754

mean along one axis:
 [-0.42812748  0.98365959 -0.5593622  -1.37184661]

sum along one axis:
 [ 0.02269766 -2.77405105]

the index of min elements
 [0 1 1 1]

selected min elements
 [-1.47670506 -0.12454182 -0.70414127 -2.56581807]

sorted index of elements along one aixs
 [[0 2 3 1]
 [3 2 1 0]]

sorted array
 [[-1.47670506 -0.12454182 -0.70414127 -2.56581807]
 [ 0.6204501   2.09186101 -0.41458314 -0.17787515]]


In [20]:
# indices
# think it like an image
x = np.random.randn(24, 24, 3)
print(x[:, :, 0].shape)
print(x[5:10, 5:10, :].shape)

(24, 24)
(5, 5, 3)
